namespace CurrencyExchange.Services.ExchangeRates.Models
{
    public class Rates
    {
        public Decimal AED { get; set; }
        public Decimal AFN { get; set; }
        public Decimal ALL { get; set; }
        public Decimal AMD { get; set; }
        public Decimal ANG { get; set; }
        public Decimal AOA { get; set; }
        public Decimal ARS { get; set; }
        public Decimal AUD { get; set; }
        public Decimal AWG { get; set; }
        public Decimal AZN { get; set; }
        public Decimal BAM { get; set; }
        public Decimal BBD { get; set; }
        public Decimal BDT { get; set; }
        public Decimal BGN { get; set; }
        public Decimal BHD { get; set; }
        public Decimal BIF { get; set; }
        public Decimal BMD { get; set; }
        public Decimal BND { get; set; }
        public Decimal BOB { get; set; }
        public Decimal BRL { get; set; }
        public Decimal BSD { get; set; }
        public Decimal BTC { get; set; }
        public Decimal BTN { get; set; }
        public Decimal BWP { get; set; }
        public Decimal BYN { get; set; }
        public Decimal BYR { get; set; }
        public Decimal BZD { get; set; }
        public Decimal CAD { get; set; }
        public Decimal CDF { get; set; }
        public Decimal CHF { get; set; }
        public Decimal CLF { get; set; }
        public Decimal CLP { get; set; }
        public Decimal CNY { get; set; }
        public Decimal COP { get; set; }
        public Decimal CRC { get; set; }
        public Decimal CUC { get; set; }
        public Decimal CUP { get; set; }
        public Decimal CVE { get; set; }
        public Decimal CZK { get; set; }
        public Decimal DJF { get; set; }
        public Decimal DKK { get; set; }
        public Decimal DOP { get; set; }
        public Decimal DZD { get; set; }
        public Decimal EGP { get; set; }
        public Decimal ERN { get; set; }
        public Decimal ETB { get; set; }
        public Decimal EUR { get; set; }
        public Decimal FJD { get; set; }
        public Decimal FKP { get; set; }
        public Decimal GBP { get; set; }
        public Decimal GEL { get; set; }
        public Decimal GGP { get; set; }
        public Decimal GHS { get; set; }
        public Decimal GIP { get; set; }
        public Decimal GMD { get; set; }
        public Decimal GNF { get; set; }
        public Decimal GTQ { get; set; }
        public Decimal GYD { get; set; }
        public Decimal HKD { get; set; }
        public Decimal HNL { get; set; }
        public Decimal HRK { get; set; }
        public Decimal HTG { get; set; }
        public Decimal HUF { get; set; }
        public Decimal IDR { get; set; }
        public Decimal ILS { get; set; }
        public Decimal IMP { get; set; }
        public Decimal INR { get; set; }
        public Decimal IQD { get; set; }
        public Decimal IRR { get; set; }
        public Decimal ISK { get; set; }
        public Decimal JEP { get; set; }
        public Decimal JMD { get; set; }
        public Decimal JOD { get; set; }
        public Decimal JPY { get; set; }
        public Decimal KES { get; set; }
        public Decimal KGS { get; set; }
        public Decimal KHR { get; set; }
        public Decimal KMF { get; set; }
        public Decimal KPW { get; set; }
        public Decimal KRW { get; set; }
        public Decimal KWD { get; set; }
        public Decimal KYD { get; set; }
        public Decimal KZT { get; set; }
        public Decimal LAK { get; set; }
        public Decimal LBP { get; set; }
        public Decimal LKR { get; set; }
        public Decimal LRD { get; set; }
        public Decimal LSL { get; set; }
        public Decimal LTL { get; set; }
        public Decimal LVL { get; set; }
        public Decimal LYD { get; set; }
        public Decimal MAD { get; set; }
        public Decimal MDL { get; set; }
        public Decimal MGA { get; set; }
        public Decimal MKD { get; set; }
        public Decimal MMK { get; set; }
        public Decimal MNT { get; set; }
        public Decimal MOP { get; set; }
        public Decimal MRO { get; set; }
        public Decimal MUR { get; set; }
        public Decimal MVR { get; set; }
        public Decimal MWK { get; set; }
        public Decimal MXN { get; set; }
        public Decimal MYR { get; set; }
        public Decimal MZN { get; set; }
        public Decimal NAD { get; set; }
        public Decimal NGN { get; set; }
        public Decimal NIO { get; set; }
        public Decimal NOK { get; set; }
        public Decimal NPR { get; set; }
        public Decimal NZD { get; set; }
        public Decimal OMR { get; set; }
        public Decimal PAB { get; set; }
        public Decimal PEN { get; set; }
        public Decimal PGK { get; set; }
        public Decimal PHP { get; set; }
        public Decimal PKR { get; set; }
        public Decimal PLN { get; set; }
        public Decimal PYG { get; set; }
        public Decimal QAR { get; set; }
        public Decimal RON { get; set; }
        public Decimal RSD { get; set; }
        public Decimal RUB { get; set; }
        public Decimal RWF { get; set; }
        public Decimal SAR { get; set; }
        public Decimal SBD { get; set; }
        public Decimal SCR { get; set; }
        public Decimal SDG { get; set; }
        public Decimal SEK { get; set; }
        public Decimal SGD { get; set; }
        public Decimal SHP { get; set; }
        public Decimal SLE { get; set; }
        public Decimal SLL { get; set; }
        public Decimal SOS { get; set; }
        public Decimal SRD { get; set; }
        public Decimal STD { get; set; }
        public Decimal SVC { get; set; }
        public Decimal SYP { get; set; }
        public Decimal SZL { get; set; }
        public Decimal THB { get; set; }
        public Decimal TJS { get; set; }
        public Decimal TMT { get; set; }
        public Decimal TND { get; set; }
        public Decimal TOP { get; set; }
        public Decimal TRY { get; set; }
        public Decimal TTD { get; set; }
        public Decimal TWD { get; set; }
        public Decimal TZS { get; set; }
        public Decimal UAH { get; set; }
        public Decimal UGX { get; set; }
        public Decimal USD { get; set; }
        public Decimal UYU { get; set; }
        public Decimal UZS { get; set; }
        public Decimal VEF { get; set; }
        public Decimal VES { get; set; }
        public Decimal VND { get; set; }
        public Decimal VUV { get; set; }
        public Decimal WST { get; set; }
        public Decimal XAF { get; set; }
        public Decimal XAG { get; set; }
        public Decimal XAU { get; set; }
        public Decimal XCD { get; set; }
        public Decimal XDR { get; set; }
        public Decimal XOF { get; set; }
        public Decimal XPF { get; set; }
        public Decimal YER { get; set; }
        public Decimal ZAR { get; set; }
        public Decimal ZMK { get; set; }
        public Decimal ZMW { get; set; }
        public Decimal ZWL { get; set; }
    }
}
